### ISSUE TITLE
Issue and a possible fix

### ISSUE THREAD

**Issue by wesam12131** [FssAy/SocietyFix#1]
I'm not sure if this is written or not but as of right now there are still some irregular people, what I purpose to fix this is maybe make this run either multiple times , you can do this by either making the script run on every world load instead of it only running on generation or even just run both on load/generation multiple times after the new NPCs generate new attractedTo parameters.

Please keep maintaining this, you don't know how much we appreicate this addon, even if they took you down off of the thunderstore we're still using your mod :)
![image](https://github.com/user-attachments/assets/0b370071-9ed9-4011-bd26-fb46dbbe0f71)

**Comment by FssAy** [comment]
This is my first ever plugin and I am not a C# dev, so there might be such issues. On top of that I didn't yet fully get through all functions and process of how the NPCs are generated. After making some tests, this code is the best I came up with.

Btw, the administrators already took the mod down lol. Funny how sexual deviations are pushed onto our society, so hard we cannot even remove the filth from our beloved games.

I'll try to fix the issues and update the installation method guide, so the Thunderstore is not needed.

**Comment by FssAy** [comment]
> there are still some irregular people

What do you mean exactly by "irregular people"?

- There shouldn't be any "non-binary" NPCs as all the genders that don't match the `birthGender` are fixed, see [here](https://github.com/FssAy/SocietyFix/blob/cd4eb49248ec6ccc80b297377c3a8e4a42f41496/Plugin.cs#L36).
- As for females that look like males it is related to the outfits and I still am not sure how to patch it as it is done after assigning a gender.
- In the relation to homosexuals I've read it's based on a random chance. I might try to override it, but it can result in more bugs, we'll see.


> making the script run on every world load 

I didn't test it yet, but that might break some things. For example current cases, or NPC behavior.

**Comment by FssAy** [comment]
> In the relation to homosexuals 

Should be fixed in the [`1.0.1`](https://github.com/FssAy/SocietyFix/releases/tag/v1.0.1) release by patching the [`GenerateSuitableGenderAndSexualityForParnter`](https://github.com/FssAy/SocietyFix/blob/0f5b5a92c4dc9347f450529b1d2ff15aca50dfd3/Plugin.cs#L71) function. Let me know if you encounter any additional issues.

**Comment by wesam12131** [comment]
> What do you mean exactly by "irregular people"?
 
 As in the homosexuals/ either sex wearing the other sex's clothing
> * In the relation to homosexuals I've read it's based on a random chance. I might try to override it, but it can result in more bugs, we'll see.

 Oh, alright.
> Btw, the administrators already took the mod down lol. Funny how sexual deviations are pushed onto our society, so hard we cannot even remove the filth from our beloved games.

Tell me about it, I was banned while replying to idiots who are mad about this mod, I asked the mod: "So I can't display my opinion but they can?" he just ended up saying yes because they're a part of a "protected group" lol.

**Comment by wesam12131** [comment]
> > In the relation to homosexuals
> 
> Should be fixed in the [`1.0.1`](https://github.com/FssAy/SocietyFix/releases/tag/v1.0.1) release by patching the [`GenerateSuitableGenderAndSexualityForParnter`](https://github.com/FssAy/SocietyFix/blob/0f5b5a92c4dc9347f450529b1d2ff15aca50dfd3/Plugin.cs#L71) function. Let me know if you encounter any additional issues.

Great to hear! I will be testing it and coming back if any bugs are found!
